Repository mediawiki-client-tools/mediawiki-dump-generator, pull requests merged in 2023-01, with the labels that each got.

#94 Properly synchronize Delay
  wikiteam3/dumpgenerator/cli/delay.py
Labels: enhancement

#97 Remove special characte from special_version.py
  wikiteam3/dumpgenerator/dump/misc/special_version.py
Labels: bug

#103 Refactor xml dump related codes and improve xmlrevision logic
  wikiteam3/dumpgenerator/api/namespaces.py
  wikiteam3/dumpgenerator/api/page_titles.py
  wikiteam3/dumpgenerator/cli/cli.py
  wikiteam3/dumpgenerator/config.py
  wikiteam3/dumpgenerator/dump/generator.py
  wikiteam3/dumpgenerator/dump/image/__init__.py
  wikiteam3/dumpgenerator/dump/image/image.py
  wikiteam3/dumpgenerator/dump/page/xmlexport/__init__.py
  wikiteam3/dumpgenerator/dump/page/xmlexport/page_xml.py
  wikiteam3/dumpgenerator/dump/page/xmlrev/__init__.py
  wikiteam3/dumpgenerator/dump/page/xmlrev/xml_revisions.py
  wikiteam3/dumpgenerator/dump/page/xmlrev/xml_revisions_page.py
  wikiteam3/dumpgenerator/dump/xmldump/__init__.py
  wikiteam3/dumpgenerator/dump/xmldump/xml_dump.py
  wikiteam3/dumpgenerator/dump/xmldump/xml_header.py
  wikiteam3/dumpgenerator/dump/xmldump/xml_integrity.py
  wikiteam3/dumpgenerator/dump/xmldump/xml_truncate.py
  wikiteam3/dumpgenerator/dump/xmlrev/xml_dump.py
  wikiteam3/dumpgenerator/dump/xmlrev/xml_revisions.py
Labels: enhancement

#104 Deprecate `truncateFilename()` and increase filename length limit.
  wikiteam3/dumpgenerator/cli/cli.py
  wikiteam3/dumpgenerator/dump/generator.py
  wikiteam3/dumpgenerator/dump/image/image.py
  wikiteam3/utils/__init__.py
  wikiteam3/utils/truncate.py
Labels: enhancement

#108 Fix some bugs in #103
  wikiteam3/dumpgenerator/api/page_titles.py
  wikiteam3/dumpgenerator/dump/page/xmlrev/xml_revisions.py
  wikiteam3/dumpgenerator/dump/xmldump/xml_dump.py
Labels: bug

#112 Improve image dump logic
  wikiteam3/dumpgenerator/dump/image/image.py
Labels: enhancement

#116 Speed up file scanning
  wikiteam3/dumpgenerator/dump/generator.py
Labels: enhancement

#119 Fix: `--xmlrevisions` and `--xmlrevisions_page` can't get any wikitext
  wikiteam3/dumpgenerator/dump/page/xmlrev/xml_revisions_page.py
Labels: bug, urgent
